### ISSUE TITLE
Cannot delete imported items that have media

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/FedoraConnector#3]
Trying to delete an imported item from Fedora gives:

exception 'Omeka\File\Exception\RuntimeException' with message 'Failed to delete "/var/www/omekas/files/original/fab502a1112c6e095123d62422f17a14551afdbd.jpeg".' in /var/www/omekas/application/src/File/Store/LocalStore.php:65
Stack trace:
#0 /var/www/omekas/application/src/File/Manager.php(78): Omeka\File\Store\LocalStore->delete('original/fab502...')
#1 /var/www/omekas/application/Module.php(128): Omeka\File\Manager->deleteOriginal(Object(Omeka\Model\Entity\Media))
#2 [internal function]: Omeka\Module->deleteMediaFiles(Object(Omeka\Event\Event))
#3 /var/www/omekas/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Omeka\Event\Event))
#4 /var/www/omekas/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('entity.remove.p...', Object(Omeka\Event\Event), NULL)
#5 /var/www/omekas/application/src/Db/Event/Subscriber/Entity.php(124): Zend\EventManager\EventManager->trigger(Object(Omeka\Event\Event))
#6 /var/www/omekas/application/src/Db/Event/Subscriber/Entity.php(63): Omeka\Db\Event\Subscriber\Entity->trigger('entity.remove.p...', Object(Doctrine\ORM\Event\LifecycleEventArgs))
#7 /var/www/omekas/vendor/doctrine/common/lib/Doctrine/Common/EventManager.php(59): Omeka\Db\Event\Subscriber\Entity->postRemove(Object(Doctrine\ORM\Event\LifecycleEventArgs))
#8 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/Event/ListenersInvoker.php(117): Doctrine\Common\EventManager->dispatchEvent('postRemove', Object(Doctrine\ORM\Event\LifecycleEventArgs))
#9 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1115): Doctrine\ORM\Event\ListenersInvoker->invoke(Object(Doctrine\ORM\Mapping\ClassMetadata), 'postRemove', Object(Omeka\Model\Entity\Media), Object(Doctrine\ORM\Event\LifecycleEventArgs), 4)
#10 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#11 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#12 /var/www/omekas/application/src/Api/Adapter/Entity/AbstractEntityAdapter.php(356): Doctrine\ORM\EntityManager->flush()
#13 /var/www/omekas/application/src/Api/Manager.php(200): Omeka\Api\Adapter\Entity\AbstractEntityAdapter->delete(Object(Omeka\Api\Request))
#14 /var/www/omekas/application/src/Api/Manager.php(116): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#15 /var/www/omekas/application/src/Mvc/Controller/Plugin/Api.php(122): Omeka\Api\Manager->delete('items', Array, Array)
#16 /var/www/omekas/application/src/Controller/Admin/ItemController.php(100): Omeka\Mvc\Controller\Plugin\Api->delete('items', Array)
#17 /var/www/omekas/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(82): Omeka\Controller\Admin\ItemController->deleteAction()
#18 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /var/www/omekas/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#20 /var/www/omekas/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /var/www/omekas/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /var/www/omekas/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#23 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#24 /var/www/omekas/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#25 /var/www/omekas/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#26 /var/www/omekas/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#27 /var/www/omekas/index.php(16): Zend\Mvc\Application->run()

**Comment by jimsafley** [comment]
This typically happens when your web server doesn't have permission to delete the file.

**Comment by patrickmj** [comment]
Checked that. Still same exception

**Comment by jimsafley** [comment]
Try `$ sudo chmod -R 777 files/`

**Comment by patrickmj** [comment]
yep. had already tried that. no dice.

**Comment by patrickmj** [comment]
well. brand new imports can be deleted, so i'll call this fixed. thanks
