### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka-s-modules/FedoraConnector#46]
Update documentation to address new features:

- Shortened Fedora container text to ID and hyperlinked to container
- Added ability to re-run job from past imports page
- Linked to advanced search results for imported items on past imports page

**Comment by katknow** [comment]
[A draft of the updates can be found here](https://github.com/omeka/omeka-s-enduser/blob/connectors-update/docs/modules/fedoraconnector.md)

**Comment by matthewjmckinley** [comment]
@katknow Both this and the DSpace updates look good to me! The only thing I see are a few stray `{target=_blank}`s in the first sentence of both that I don't believe are necessary?

**Comment by allanaaa** [comment]
> @katknow Both this and the DSpace updates look good to me! The only thing I see are a few stray `{target=_blank}`s in the first sentence of both that I don't believe are necessary?

Those will render in markdown, they just ensure the links open in new tabs. Ignore them!

**Comment by katknow** [comment]
Since things look good to go I will go ahead and merge the branch!
