### ISSUE TITLE
What to do with import jobs that have been undone?

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/FedoraConnector#5]
The undo interface starts with a list of all the import jobs done by the module. But, since we're not deleting jobs to keep the trail, need to figure out what else in the interface to add to tell admins what jobs have been undone (or at least have no items, which isn't necessarily the same thing)
- Total number of items from the import job?
- Whether there is a successful undo job for that import job (hard to dig up from the args, but possible)?
- Add a comment to import jobs (would require a core change to jobs)?

**Comment by patrickmj** [comment]
@jimsafley @zerocrates any thoughts on this issue about undone import jobs? Thanks

**Comment by jimsafley** [comment]
The effect a job has is inconsequential to the job itself. The only thing that matters is whether the job was successfully completed. If you want to record an undone import, you can make the undo process a job.

**Comment by patrickmj** [comment]
@jimsafley the undoing is currently a job. I was thinking along the lines of the interface 1) no longer showing import jobs that were successfully undone, and 2) showing information about the import jobs so people know which one they want to undo

**Comment by patrickmj** [comment]
closed in 4d85b
